apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  labels:
    app: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: laravel-app
        image: gbxnga/laravel-aws-eks:v2
        ports:
        - containerPort: 80 
        resources:
          limits:
            cpu: 0.5
            memory: 1Gi
          requests:
            cpu: 0.3
            memory: 500Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 3 
        env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_DATABASE
          value: laravel_aws_eks
        - name: DB_USERNAME
          value: app 
        - name: DB_PASSWORD
          value: password
